project:
  type: website
  output-dir: docs
  resources:
    - files/zip_lessons_code/AQILessonCode.zip
    - files/zip_lessons_code/BiodiversityLessonCode.zip
    - files/zip_lessons_code/ClimateChangeLessonCode.zip
    - lesson_plans/code_files/SalmonLessonCode.zip
    - files/zip_lessons_code/SeaLevelsLessonCode.zip
  
webr: 
  packages: ['tidyverse']
  
website:
  title: "6-12 Data Science Resources"
  navbar: 
    left: 
    - text: Lesson Plans 
      menu: 
        - lesson_plans/lesson_links.qmd
    - text: Online Tutorials
      menu:
        - tutorials/salmon_lesson.qmd
#    background: "info" https://quarto.org/docs/websites/website-navigation.html
#    foreground: "light"
    
format:
  html:
    theme: yeti
#    theme: lux sandstone yeti
    css: styles.css
    toc: true