project:
  type: website
  output-dir: docs
  resources:
    - files/lesson_code_zips/AQILessonCode.zip
    - files/lesson_code_zips/BiodiversityLessonCode.zip
    - files/lesson_code_zips/ClimateChangeLessonCode.zip
    - files/lesson_code_zips/SalmonLessonCode.zip
    - files/lesson_code_zips/SeaLevelsLessonCode.zip
    - files/data/temp_data.csv
    - files/data/owid_co2_data_2.csv
    - files/Bonneville_Dam_1939_2023_Chinook_CSV.csv
  
webr: 
  packages: ['tidyverse']
  
website:
  title: "6-12 Data Science Resources"
  navbar: 
    left: 
    - text: Lesson Plans 
      menu: 
        - lesson_plans/lesson_links.qmd
    - text: Online Tutorials
      menu:
        - tutorials/salmon_lesson.qmd
        - tutorials/climate_change_tutorial.qmd
#    background: "info" https://quarto.org/docs/websites/website-navigation.html
#    foreground: "light"
    
format:
  html:
    theme: yeti
#    theme: lux sandstone yeti
    css: styles.css
    toc: true