project:
  type: website
  output-dir: docs
  resources:
    - files
    - js
    - styles1.css
  
#webr: 
#  packages: ['tidyverse']

#number-sections: true
#number-depth: 2


website:
  title: "6-12 Data Science Resources"
  repo-url: https://github.com/Lewis-and-Clark-Data-Science/6-12-Data-Science-Resources
  repo-actions: source
  site-url: https://lewis-and-clark-data-science.github.io/6-12-Data-Science-Resources/
  favicon: files/figures/data-science-icon.png
  back-to-top-navigation: true
  navbar: 
    left: 
    - text: Lesson Plans 
      menu: 
        - lesson_plans/lesson_links.qmd
        - text: "Salmon Return at Bonneville Dam"
          href: lesson_plans/Salmon_lesson.qmd
        - lesson_plans/AQI_lessons/AQI_lesson.qmd
        - lesson_plans/Biodiversity_lesson.qmd
        - lesson_plans/climate_lesson.qmd
        - lesson_plans/sea_levels_lesson.qmd
    - text: Online Tutorials
      menu:
        - tutorials/salmon_tutorial.qmd
        - tutorials/climate_change_tutorial.qmd
        - tutorials/biodiversity_tutorial.qmd
        - tutorials/AQI_tutorial.qmd
        - tutorials/AQI_tutorial_advanced.qmd
        - tutorials/sealevel_tutorial.qmd
    - text: Resources
      menu:
        - resources/resources.qmd
        - resources/cheatsheet.qmd
  
  sidebar:
    - id: tutorials/AQI_tutorial.qmd
      title: "Air Quality Tutorials"
      style: "docked"
      collapse-level: 2
      contents: 
        - section: "Air Quality Tutorials"
          contents: 
            - tutorials/AQI_tutorial.qmd
            - tutorials/AQI_tutorial_advanced.qmd
    - id: lesson_plans/Salmon_lesson.qmd
      title: "Salmon Crossing Lesson Materials"
      style: "docked"
      collapse-level: 2
      contents:
        - section: "Salmon Crossing Lesson Materials"
          contents:
              - text: "Lesson Overview - Salmon Return at Bonneville Dam" 
                href: lesson_plans/Salmon_lesson.qmd
              - text: "Lesson Plan - Salmon Return at Bonneville Dam"
                href: lesson_plans/Salmon_lesson_plan.qmd
    - id: lesson_plans/AQI_lessons/AQI_lesson.qmd
      title: "Air Quality Lesson Materials"
      style: "docked"
      collapse-level: 5
      contents:
          - text: "Air Quality Lessons Landing Page" 
            href: lesson_plans/AQI_lessons/AQI_lesson.qmd
          - section: "Middle School"
            contents: 
              - lesson_plans/AQI_lessons/AQI_middle_overview.qmd
              - lesson_plans/AQI_lessons/AQI_middle_lesson_plan.qmd
          - section: "High School"
            contents: 
              - lesson_plans/AQI_lessons/AQI_high_overview.qmd
              - lesson_plans/AQI_lessons/AQI_high_lesson_plan.qmd
  
  #sidebar: 
  #    style: "docked"
  #    - id: tutorials/AQI_tutorial.qmd
  #      contents:
  #       - section: "AQI tutorials"
  #         href: tutorials/AQI_tutorial.qmd
  #         contents: 
  #            - tutorials/AQI_tutorial.qmd
  #            - tutorials/AQI_tutorial_advanced.qmd
              
    
#    background: "info" https://quarto.org/docs/websites/website-navigation.html
#    foreground: "light"
  

format:
  html:
    theme: 
      - yeti
      #    theme: lux sandstone yeti
    css: styles1.css
    toc: true
    toc-depth: 3
    knitr: 
      opts_chunk: 
        dev: "ragg_png"
        dpi: 300