---
title: 6-12 Data Science Resources
---

Welcome! This site includes lots of resources for using data science in your middle or high school classroom. 

### Site Navigation

Under [**Lesson Plans**](https://lewis-and-clark-data-science.github.io/6-12-Data-Science-Resources/lesson_plans/lesson_links.html), you'll find lesson plans for various STEM subjects and grade levels that all incorporate some data science. Each lesson plan includes an overview page with materials, lesson description, and reflections for teachers who have taught the lesson, as well as a lesson plan page including powerpoints, worksheets, code files, graphs, and more.

Under **Online Tutorials** (see menu at the top of the site), you'll find tutorials that can be done directly on this website which can be used to teach and learn about data science and basic R coding. These correspond with the lesson plans and can often be used *instead of* downloading the code files embedded in the Lesson Plans. They generally require minimal to no experience in R coding. 

Under [**Resources**](https://lewis-and-clark-data-science.github.io/6-12-Data-Science-Resources/resources/resources.html), you'll find links to other sites with educational resources for teaching and learning about data science!

**Browser information**: The Online Tutorials will not run on safari. Use chrome, firefox, or another browser instead. 


