---
title: Lesson Plans Landing Page
---

## About the lessons

**How were these lessons created?**

Welcome! On this site, we've developed lesson plans that incorporate an introduction to data science within various subjects. The lessons were created out of a collaboration between Lewis & Clark College faculty, undergraduate students, University of Arizona faculty and Portland, OR area 6-12 educators. Each Lewis & Clark student partnered with a couple middle or high school teachers and together they co-developed and taught a data science lesson that was integrated into the teachers' broader curriculum/unit. All participants gathered during a week long summer workshop to create the initial lessons and then continued developing them throughout the 2023-2024 academic year. After the lessons were taught, all the participants of this project met to reflect on the lessons and make any modifications. We are sharing the final lesson plans on this website!

**Lesson levels and subjects**

The lesson plan levels range from middle to high school, spanning various subjects including physics, chemistry, and biology, and they vary in their data science and/or coding difficulty.

**Data science in the lessons**

For each lesson, a Lewis & Clark (LC) student studying data science gave 6th-12th grade students an introduction to data science. Data science is a very broad term, so the lessons vary in what aspects of data science they focus on. For most lessons, LC undergraduates wrote R code to help visualize a science phenomenon that middle/high school students were learning about in their classroom (e.g. salmon return at the Bonneville Dam, air quality levels in Portland, etc). The LC student then co-taught the data science lesson with the teacher they partnered with, often including an introduction to "what is data science", a demonstration of R coding, and/or an analysis of graphs and visualizations.

**Coding in the lessons (NOT required)**

Though most lessons were originally taught demonstrating some basic R coding, they are easily adaptable if teachers prefer not to incorporate the coding aspects. Additionally, since the lessons were taught, we've created online tutorials that teachers can use to introduce their students to R coding. These tutorials are specifically designed for students (and teachers) who have not coded in R before and help students work through a basic understanding of data science. There are tutorials that correspond with most of the lessons on this site and can be used if you don't have a Lewis & Clark student to help with the coding aspect!

## Lesson Plans

| Lesson Title | Grade Level   | Subject/Unit | Time                |
|---------------|---------------|---------------|---------------|
| [Salmon Return](https://lewis-and-clark-data-science.github.io/6-12-Data-Science-Resources/lesson_plans/Salmon_lesson.html) | 6th-8th | Ecology | 3 45-minute lessons |
| [Air Quality - Middle School](https://lewis-and-clark-data-science.github.io/6-12-Data-Science-Resources/lesson_plans/AQI_lessons/AQI_middle_overview.html) | 6th-8th | Climate Change | 3 40-minute lessons |
| [Analyzing Planetary Data with R](https://lewis-and-clark-data-science.github.io/6-12-Data-Science-Resources/lesson_plans/COR_lesson.html) | 6th-12th | Astronomy | 1 50-minute lesson|
| [Air Quality - High School](https://lewis-and-clark-data-science.github.io/6-12-Data-Science-Resources/lesson_plans/AQI_lessons/AQI_high_overview.html) | 10th-12th | Environmental Science or Biology | 3-4 90-minute lessons|
| [Biodiversity](https://lewis-and-clark-data-science.github.io/6-12-Data-Science-Resources/lesson_plans/Biodiversity_lesson.html)| 9th-12th | Biology (intro, honors, IB options) | 1 90-minute lesson (plus extra resources for larger unit) | 
| [Climate Change](https://lewis-and-clark-data-science.github.io/6-12-Data-Science-Resources/lesson_plans/climate_lesson.html) | 9th-12th | Physics | 4 lessons | 
| [Sea Levels](https://lewis-and-clark-data-science.github.io/6-12-Data-Science-Resources/lesson_plans/sea_levels_lesson.html) | 9th-12th (adaptable for middle school) | Chemistry - KMT and Climate Change | 2-3 95-minute lessons |

: Lessons {.striped .light .bordered}


## Optional: Downloadable R files

As mentioned above, there are options within each lesson to download R code and demonstrate coding to your class. If you have not coded in R before, we recommend you use the online tutorials instead (see the menu at the top of the site). These are beginner tutorials that go along with the lesson plans on this website.

If you want to use the R code files, you can download them below. Each link below will download a .zip file containing the code and datasets for each lesson. We recommend you open the files using [Rstudio desktop](https://posit.co/download/rstudio-desktop/) or [posit.cloud](https://posit.cloud/content/yours?sort=name_asc) (an online version of Rstudio).

If you want to improve your R skills, check out the [Learning R Tutorials section](#sec-DITW) for more in depth R tutorials that cover basic R commands, data wrangling and graphing.

::: columns
::: {.column width=50%}
### Middle School Lessons

[Salmon Lesson Code .zip file](https://lewis-and-clark-data-science.github.io/6-12-Data-Science-Resources/files/lesson_code_zips/SalmonLessonCode.zip)

[Air Quality Lesson Code .zip file](https://lewis-and-clark-data-science.github.io/6-12-Data-Science-Resources/files/lesson_code_zips/AQILessonCode.zip)

[Planetary Data Lesson code .zip file](https://lewis-and-clark-data-science.github.io/6-12-Data-Science-Resources/files/lesson_code_zips/CORLessonCode.zip)
:::
::: {.column width=50%}
### High School Lessons

[Air Quality Lesson Code .zip file](https://lewis-and-clark-data-science.github.io/6-12-Data-Science-Resources/files/lesson_code_zips/AQILessonCode.zip)

[Biodiversity Lesson Code .zip file](https://lewis-and-clark-data-science.github.io/6-12-Data-Science-Resources/files/lesson_code_zips/BiodiversityLessonCode.zip)

[Climate Change Lesson Code .zip file](https://lewis-and-clark-data-science.github.io/6-12-Data-Science-Resources/files/lesson_code_zips/ClimateChangeLessonCode.zip)

[Sea Levels Lesson Code .zip file](https://lewis-and-clark-data-science.github.io/6-12-Data-Science-Resources/files/lesson_code_zips/SeaLevelsLessonCode.zip)
:::
:::

## Learning R Tutorial (more in-depth) {#sec-DITW}

Below are R tutorials developed for Lewis & Clark College's Data in the Wild data science course. They cover basic data wrangling, graphing with ggplot and inferential statistics. These tutorials go much more in depth into R coding than the "Online Tutorials" on this site. We recommend these for any teacher who wants to improve their R skills! 

To use the tutorials, download the following .zip files and open in an R project on posit.cloud or R studio desktop. Each file contains modules which include a code-a-long, practice problems and homework.

We recommend you begin with the code-a-long and refer to the code-a-long key to determine which commands to type in the code-a-long. Then, proceed to the homework and practice problems for more practice.

Also, check out this [video](https://drive.google.com/file/d/1bBlisDortndIVptEwwFgtRePX_Vozmxk/view?usp=sharing) for a video walk-through of how to download and use these files. 

[Module 1 - Basic data wrangling .zip file](https://lewis-and-clark-data-science.github.io/6-12-Data-Science-Resources/files/lesson_code_zips/DITW_Module1.zip)

[Module 2 - Plotting with ggplot .zip file](https://lewis-and-clark-data-science.github.io/6-12-Data-Science-Resources/files/lesson_code_zips/DITW_Module2.zip)

[Module 3 - Inferential Statistics .zip file](https://lewis-and-clark-data-science.github.io/6-12-Data-Science-Resources/files/lesson_code_zips/DITW_Inferential_stats.zip)
